-- Create the questions table if it doesn't exist
create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  question text not null,
  answer text,
  author_name text default 'Anonymous',
  is_answered boolean default false
);

-- Enable Row Level Security (RLS)
alter table public.questions enable row level security;

-- Create policies (using do block to avoid "already exists" errors)
do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Enable read access for all users' and tablename = 'questions') then
    create policy "Enable read access for all users" on public.questions for select using (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Enable insert access for all users' and tablename = 'questions') then
    create policy "Enable insert access for all users" on public.questions for insert with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Enable update access for all users' and tablename = 'questions') then
    create policy "Enable update access for all users" on public.questions for update using (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Enable delete access for all users' and tablename = 'questions') then
    create policy "Enable delete access for all users" on public.questions for delete using (true);
  end if;
end
$$;

-- Create the events table if it doesn't exist
create table if not exists public.events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  date date not null,
  body text,
  image_url text,
  is_upcoming boolean default true,
  category text default 'general' -- 'general' (STUCO) or 'club'
);

-- Add is_upcoming column if it doesn't exist (in case table existed but was old)
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name='events' and column_name='is_upcoming') then
    alter table public.events add column is_upcoming boolean default true;
  end if;
end
$$;

-- Add category column if it doesn't exist
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name='events' and column_name='category') then
    alter table public.events add column category text default 'general';
  end if;
end
$$;


-- Enable RLS for events
alter table public.events enable row level security;

-- Policies for events
do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Enable read access for all users' and tablename = 'events') then
    create policy "Enable read access for all users" on public.events for select using (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Enable insert access for all users' and tablename = 'events') then
    create policy "Enable insert access for all users" on public.events for insert with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Enable update access for all users' and tablename = 'events') then
    create policy "Enable update access for all users" on public.events for update using (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Enable delete access for all users' and tablename = 'events') then
    create policy "Enable delete access for all users" on public.events for delete using (true);
  end if;
end
$$;

-- Create the storage bucket for event images if it doesn't exist
insert into storage.buckets (id, name, public)
values ('event-images', 'event-images', true)
on conflict (id) do nothing;

-- Policies for storage bucket (using do block to avoid "already exists" errors)
do $$
begin
  -- Allow public read access to images
  if not exists (select 1 from pg_policies where policyname = 'Public Access' and tablename = 'objects' and schemaname = 'storage') then
    create policy "Public Access" on storage.objects for select using ( bucket_id = 'event-images' );
  end if;
  
  -- Allow anyone to upload images (In a real app, restrict this to admin)
  if not exists (select 1 from pg_policies where policyname = 'Public Upload' and tablename = 'objects' and schemaname = 'storage') then
    create policy "Public Upload" on storage.objects for insert with check ( bucket_id = 'event-images' );
  end if;
  
  -- Allow anyone to delete images (In a real app, restrict this to admin)
  if not exists (select 1 from pg_policies where policyname = 'Public Delete' and tablename = 'objects' and schemaname = 'storage') then
    create policy "Public Delete" on storage.objects for delete using ( bucket_id = 'event-images' );
  end if;
end
$$;

-- Execute this in the Supabase SQL Editor
