-- Create the questions table
create table public.questions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  question text not null,
  answer text,
  author_name text default 'Anonymous',
  is_answered boolean default false
);

-- Enable Row Level Security (RLS)
alter table public.questions enable row level security;

-- Create policies (Adjust based on your security needs)
-- Allow anyone to read questions
create policy "Enable read access for all users" on public.questions
  for select using (true);

-- Allow anyone to insert questions (asking)
create policy "Enable insert access for all users" on public.questions
  for insert with check (true);

-- Allow public updates (for admin answering - in a real app, strict RLS with auth is better)
-- Since we are using client-side admin password without Supabase Auth, we must allow public updates
-- BUT we can restrict it to only updating 'answer' and 'is_answered' if possible, 
-- or just allow it for now as per the current 'admin' implementation.
create policy "Enable update access for all users" on public.questions
  for update using (true);

-- Allow public delete
create policy "Enable delete access for all users" on public.questions
  for delete using (true);

-- Execute this in the Supabase SQL Editor
